# Generated by Django 3.2.9 on 2022-07-17 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizTable',
            fields=[
                ('quizname', models.CharField(max_length=50)),
                ('quiz_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('quiz_desc', models.TextField()),
                ('quiz_time', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('most_correctly_answered_question', models.IntegerField()),
                ('most_incorrectly_answered_question', models.IntegerField()),
                ('quiz_id', models.ForeignKey(db_column='quiz_id', on_delete=django.db.models.deletion.CASCADE, to='QuizApp.quiztable')),
            ],
        ),
        migrations.AddField(
            model_name='quiztable',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='QuizApp.usertable'),
        ),
        migrations.CreateModel(
            name='QuizExamTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_username', models.CharField(max_length=30)),
                ('ipaddress', models.CharField(max_length=15)),
                ('time_of_joining', models.DateTimeField()),
                ('score', models.IntegerField()),
                ('quiz_id', models.ForeignKey(db_column='quiz_id', on_delete=django.db.models.deletion.CASCADE, to='QuizApp.quiztable')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField()),
                ('question', models.TextField()),
                ('option_1', models.CharField(max_length=200)),
                ('option_2', models.CharField(max_length=200)),
                ('option_3', models.CharField(max_length=200)),
                ('option_4', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=8)),
                ('quiz_id', models.ForeignKey(db_column='quiz_id', on_delete=django.db.models.deletion.CASCADE, to='QuizApp.quiztable')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswerTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_username', models.CharField(max_length=30)),
                ('question', models.TextField(default=None)),
                ('answer', models.CharField(max_length=8)),
                ('score', models.IntegerField()),
                ('quiz_id', models.ForeignKey(db_column='quiz_id', on_delete=django.db.models.deletion.CASCADE, to='QuizApp.quiztable')),
            ],
        ),
    ]
